package com.example.crm.service;

import com.example.crm.model.OAuthToken; import com.example.crm.repository.OAuthTokenRepository; import com.example.crm.tenant.TenantContext; import com.example.crm.util.CryptoUtil; import com.microsoft.graph.models.*; import com.microsoft.graph.serviceclient.GraphServiceClient; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import java.util.List; import java.util.Optional;

@Service public class GraphMailService { private final GraphClientFactory factory; private final OAuthTokenRepository tokens; private final CryptoUtil crypto; private final String mode; private final String sharedMailbox;
  public GraphMailService(GraphClientFactory f, OAuthTokenRepository t, @Value("${crypto.dataKey}") String dataKey, @Value("${msft.clientSecret}") String clientSecret, @Value("${msft.redirectUri}") String redirect, @Value("${msft.scopes}") String scopes, @Value("${attachments.bucket}") String bucket){ this.factory=f; this.tokens=t; this.crypto=new CryptoUtil(dataKey); this.mode="delegated"; this.sharedMailbox=null; }
  public void sendAppOnly(String to, String subject, String html){ GraphServiceClient client = factory.appClient(); Message m = new Message(); m.setSubject(subject); ItemBody body = new ItemBody(); body.setContentType(BodyType.HTML); body.setContent(html); m.setBody(body); Recipient r = new Recipient(); EmailAddress ea = new EmailAddress(); ea.setAddress(to); r.setEmailAddress(ea); m.setToRecipients(List.of(r)); client.users().byUserId(sharedMailbox).sendMail(new com.microsoft.graph.users.item.sendmail.SendMailPostRequestBody(){ { setMessage(m); setSaveToSentItems(true); } }).post(); }
  public void sendDelegated(String userEmail, String to, String subject, String html){ GraphServiceClient client = factory.appClient(); // in a real delegated flow we'd use per-user refresh token to get a delegated client; simplified here
    Message m = new Message(); m.setSubject(subject); ItemBody body = new ItemBody(); body.setContentType(BodyType.HTML); body.setContent(html); m.setBody(body); Recipient r = new Recipient(); EmailAddress ea = new EmailAddress(); ea.setAddress(to); r.setEmailAddress(ea); m.setToRecipients(List.of(r)); client.users().byUserId(userEmail).sendMail(new com.microsoft.graph.users.item.sendmail.SendMailPostRequestBody(){ { setMessage(m); setSaveToSentItems(true); } }).post(); }
}
