package com.example.crm.service;

import com.example.crm.dto.PresignRequest; import com.example.crm.dto.PresignResponse; import com.example.crm.model.Attachment; import com.example.crm.repository.AttachmentRepository; import com.example.crm.tenant.TenantContext; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import org.springframework.data.domain.Page; import org.springframework.data.domain.PageRequest;
import software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider; import software.amazon.awssdk.regions.Region; import software.amazon.awssdk.services.s3.S3Configuration; import software.amazon.awssdk.services.s3.presigner.S3Presigner; import software.amazon.awssdk.services.s3.model.PutObjectRequest; import software.amazon.awssdk.services.s3.presigner.model.PutObjectPresignRequest; import java.time.Duration; import java.util.HashMap;

@Service public class S3PresignService { private final String bucket; private final Region region; private final AttachmentRepository repo; private final S3Presigner presigner; public S3PresignService(@Value("${attachments.bucket}") String bucket, @Value("${aws.region}") String region, AttachmentRepository repo){ this.bucket=bucket; this.region=Region.of(region); this.repo=repo; this.presigner = S3Presigner.builder().region(this.region).credentialsProvider(DefaultCredentialsProvider.create()).serviceConfiguration(S3Configuration.builder().build()).build(); }
  public PresignResponse presign(PresignRequest req){ String tenant = TenantContext.getTenantId(); String objectKey = (tenant!=null? tenant+"/":"") + req.getEntityType()+"/"+req.getEntityId()+"/"+System.currentTimeMillis()+"-"+req.getFileName(); var put = PutObjectRequest.builder().bucket(bucket).key(objectKey).contentType(req.getContentType()).build(); var po = PutObjectPresignRequest.builder().signatureDuration(Duration.ofMinutes(10)).putObjectRequest(put).build(); var presigned = presigner.presignPutObject(po); var headers = new HashMap<String,String>(); presigned.signedHeaders().forEach((k,v)-> headers.put(k, String.join(",", v))); return new PresignResponse(presigned.url().toString(), headers, objectKey, "s3", bucket); }
  public Page<Attachment> list(String type, String id, int page, int size){ return repo.findByTenantIdAndEntityTypeAndEntityId(TenantContext.getTenantId(), type, id, PageRequest.of(page, size)); }
  public Attachment saveMeta(Attachment a){ a.setTenantId(TenantContext.getTenantId()); a.setBucket(bucket); a.setProvider("s3"); return repo.save(a); }
}
